language: node_js
node_js:
  - '8'
install:
  - npm install -g @vue/cli
script:
  - npm install
  - npm run build
cache:
  directories:
    - 'node_modules'
notifications:
  email: false
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: /dist
  github-token: $GITHUB_TOKEN
  repo: satishjhanwer/testing-travisci
  keep-history: true
  target-branch: master
  on:
    branch: master
